version: '3.8'

services:
  postportal:
    image: hub.docker.visnovsky.us/post-portal:latest
    container_name: post-portal
    restart: unless-stopped
    ports:
      - "${PORT:-80}:80"
    env_file:
      - .env
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_AUTH: ${SMTP_AUTH}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
    volumes:
      - db_data:/var/lib/mysql
      - ./logs:/var/www/log
      - ./storage:/var/www/html/storage
    networks:
      - postportal-network

networks:
  postportal-network:
    driver: bridge

volumes:
  db_data:
