services:
  postportal:
    image: hub.docker.visnovsky.us/library/post-portal:latest
    container_name: post-portal
    restart: unless-stopped
    ports:
      - "${PORT}:80"
    env_file:
      - .env
    environment:
      MYSQL_HOST: localhost
    volumes:
      - db_data:/var/lib/mysql
      - ./logs:/var/www/html/logs
      - ./storage:/var/www/html/storage
    networks:
      - postportal-network

networks:
  postportal-network:
    driver: bridge

volumes:
  db_data:
